import { 
  UserProfile, 
  SwapRequest, 
  SkillCategoryDefinition, 
  AdminReport, 
  PlatformAnnouncement,
  PlatformNotification
} from './types';

export const SKILL_CATEGORIES: SkillCategoryDefinition[] = [
  {
    id: 'tech',
    name: 'Programming & Tech',
    description: 'Web, Mobile, AI/ML, Cloud Architecture & DevOps',
    iconName: 'Code',
    popularSkills: ['React & TypeScript', 'Python & AI', 'Rust', 'Docker & Kubernetes', 'Node.js', 'PostgreSQL'],
    colorTheme: 'from-blue-500/10 to-indigo-500/10 border-blue-500/20 text-blue-600',
  },
  {
    id: 'design',
    name: 'Design & Creative',
    description: 'UI/UX Design, Figma, 3D Blender, Motion & Branding',
    iconName: 'Palette',
    popularSkills: ['Figma Design Systems', '3D Modeling (Blender)', 'Brand Identity', 'Motion Design', 'Typography'],
    colorTheme: 'from-purple-500/10 to-pink-500/10 border-purple-500/20 text-purple-600',
  },
  {
    id: 'languages',
    name: 'Languages & Culture',
    description: 'Conversational Fluency, Accent Training, Grammar & Slang',
    iconName: 'Globe',
    popularSkills: ['Spanish (C1)', 'Japanese (N2/N1)', 'French Conversational', 'Mandarin Chinese', 'German'],
    colorTheme: 'from-emerald-500/10 to-teal-500/10 border-emerald-500/20 text-emerald-600',
  },
  {
    id: 'music',
    name: 'Music & Audio',
    description: 'Guitar, Music Production, Piano, Sound Design & Mixing',
    iconName: 'Music',
    popularSkills: ['Ableton Live Production', 'Acoustic & Electric Guitar', 'Classical Piano', 'Vocal Coaching', 'Audio Mixing'],
    colorTheme: 'from-amber-500/10 to-orange-500/10 border-amber-500/20 text-amber-600',
  },
  {
    id: 'business',
    name: 'Business & Growth',
    description: 'Product Management, SEO, Startup Pitching, Financial Modeling',
    iconName: 'TrendingUp',
    popularSkills: ['Product Discovery', 'Technical SEO', 'Pitch Deck Crafting', 'Copywriting & Sales', 'Data Analysis'],
    colorTheme: 'from-cyan-500/10 to-blue-500/10 border-cyan-500/20 text-cyan-600',
  },
  {
    id: 'culinary',
    name: 'Culinary & Crafts',
    description: 'Sourdough Baking, Artisan Espresso, Woodworking, Pottery',
    iconName: 'Utensils',
    popularSkills: ['Sourdough Bread Craft', 'Specialty Coffee Brewing', 'Pottery & Ceramics', 'Italian Pasta Making'],
    colorTheme: 'from-rose-500/10 to-pink-500/10 border-rose-500/20 text-rose-600',
  },
  {
    id: 'health',
    name: 'Health & Fitness',
    description: 'Vinyasa Yoga, Marathon Coaching, Nutrition, Strength Training',
    iconName: 'HeartPulse',
    popularSkills: ['Vinyasa Yoga', 'Marathon Training Plans', 'Meal Prep & Nutrition', 'Olympic Weightlifting'],
    colorTheme: 'from-lime-500/10 to-green-500/10 border-lime-500/20 text-lime-600',
  },
  {
    id: 'academics',
    name: 'Academics & Science',
    description: 'Calculus, Statistics, Physics, Research Paper Writing',
    iconName: 'GraduationCap',
    popularSkills: ['Bayesian Statistics', 'Linear Algebra & Calculus', 'Academic Paper Peer Review', 'Astrophysics Intro'],
    colorTheme: 'from-indigo-500/10 to-violet-500/10 border-indigo-500/20 text-indigo-600',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'u-alice',
    name: 'Alice Designer',
    username: 'alice_designer',
    email: 'alice@hackathon.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'admin',
    headline: 'Senior UI/UX Designer & Design System Lead (Platform Admin)',
    bio: 'Figma and Photoshop specialist with passion for design systems, accessible UI, and micro-interactions. Looking to expand into Python backend servers and SQL databases!',
    location: 'New York, USA',
    timezone: 'UTC-5 (EST)',
    rating: 5.0,
    reviewsCount: 19,
    completedSwapsCount: 16,
    joinDate: 'Jan 2024',
    isVerified: true,
    skillsOffered: [
      {
        id: 'sk-alice-1',
        name: 'Figma',
        category: 'Design & Creative',
        level: 'Expert',
        yearsOfExperience: 6,
        description: 'Auto layout, design tokens, nested components, and clickable interactive prototypes.',
        tags: ['Figma', 'UI/UX', 'Design Systems'],
        endorsements: 42,
      },
      {
        id: 'sk-alice-2',
        name: 'Photoshop',
        category: 'Design & Creative',
        level: 'Advanced',
        yearsOfExperience: 5,
        description: 'Photo retouching, banner composition, and visual brand assets.',
        tags: ['Photoshop', 'Branding', 'Graphics'],
        endorsements: 28,
      },
      {
        id: 'sk-alice-3',
        name: 'UI/UX',
        category: 'Design & Creative',
        level: 'Expert',
        yearsOfExperience: 7,
        description: 'User flows, wireframing, usability heuristics, and user research.',
        tags: ['UI/UX', 'Wireframes', 'Research'],
        endorsements: 36,
      },
    ],
    skillsWanted: [
      {
        id: 'w-alice-1',
        name: 'Python',
        category: 'Programming & Tech',
        targetLevel: 'Intermediate',
        learningGoal: 'Build backend APIs with FastAPI / Flask and script automated design asset generators.',
        priority: 'High',
      },
      {
        id: 'w-alice-2',
        name: 'SQL',
        category: 'Programming & Tech',
        targetLevel: 'Beginner',
        learningGoal: 'Master PostgreSQL querying, joins, and data schemas.',
        priority: 'Medium',
      },
    ],
    availability: [
      { id: 'av-al-1', day: 'Sat', times: ['Morning', 'Afternoon'], preferredFormat: 'Video Call' },
      { id: 'av-al-2', day: 'Sun', times: ['Morning', 'Afternoon'], preferredFormat: 'Code / Design Review' },
    ],
    preferredFormats: ['Video Call', 'Code / Design Review'],
    privacy: {
      isProfilePublic: true,
      showEmail: true,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [
      {
        id: 'rev-al-1',
        swapId: 'sw-dummy-1',
        reviewerId: 'u-charlie',
        reviewerName: 'Charlie Data',
        reviewerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        skillExchanged: 'Figma & UI/UX',
        comment: 'Alice is an incredible designer! Highly recommend swapping skills with her. She turned my messy dashboard into a clean, modern SaaS UI.',
        date: '1 day ago',
        punctualityScore: 5,
        clarityScore: 5,
        badges: ['Super Clear', 'Creative Genius', 'Patient Mentor'],
      },
    ],
  },
  {
    id: 'u-bob',
    name: 'Bob The Dev',
    username: 'bob_dev',
    email: 'bob@hackathon.com',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    role: 'user',
    headline: 'Full-Stack Developer • Python, React & Node.js Engineer',
    bio: 'Software engineer building web apps and cloud APIs. Happy to teach Python and React in exchange for Figma UI design secrets and advanced CSS animation techniques!',
    location: 'London, UK',
    timezone: 'UTC+0 (GMT)',
    rating: 4.88,
    reviewsCount: 14,
    completedSwapsCount: 12,
    joinDate: 'Feb 2024',
    isVerified: true,
    skillsOffered: [
      {
        id: 'sk-bob-1',
        name: 'Python',
        category: 'Programming & Tech',
        level: 'Expert',
        yearsOfExperience: 5,
        description: 'Backend services, async programming, data processing, and automation scripts.',
        tags: ['Python', 'FastAPI', 'Backend'],
        endorsements: 31,
      },
      {
        id: 'sk-bob-2',
        name: 'React',
        category: 'Programming & Tech',
        level: 'Advanced',
        yearsOfExperience: 4,
        description: 'Modern React 19, hooks, custom state management, and performance tuning.',
        tags: ['React', 'TypeScript', 'Frontend'],
        endorsements: 27,
      },
      {
        id: 'sk-bob-3',
        name: 'Node.js',
        category: 'Programming & Tech',
        level: 'Advanced',
        yearsOfExperience: 4,
        description: 'RESTful APIs, middleware architecture, Express and authentication.',
        tags: ['Node.js', 'Express', 'APIs'],
        endorsements: 22,
      },
    ],
    skillsWanted: [
      {
        id: 'w-bob-1',
        name: 'Figma',
        category: 'Design & Creative',
        targetLevel: 'Intermediate',
        learningGoal: 'Design realistic mockups and learn Auto Layout for fast prototyping.',
        priority: 'High',
      },
      {
        id: 'w-bob-2',
        name: 'CSS',
        category: 'Programming & Tech',
        targetLevel: 'Advanced',
        learningGoal: 'Master CSS grid, subgrid, container queries, and glassmorphism styling.',
        priority: 'Medium',
      },
    ],
    availability: [
      { id: 'av-bob-1', day: 'Mon', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-bob-2', day: 'Wed', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-bob-3', day: 'Fri', times: ['Evening'], preferredFormat: 'Live Chat' },
    ],
    preferredFormats: ['Video Call', 'Live Chat'],
    privacy: {
      isProfilePublic: true,
      showEmail: false,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [],
  },
  {
    id: 'u-charlie',
    name: 'Charlie Data',
    username: 'charlie_data',
    email: 'charlie@hackathon.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'user',
    headline: 'Data Engineer & SQL Expert • Postgres Performance Tuning',
    bio: 'Database specialist with 6+ years optimizing Postgres queries, data pipelines, and analytics warehouses. Looking to learn React to build interactive internal analytics tools!',
    location: 'Remote, Worldwide',
    timezone: 'UTC+2 (EET)',
    rating: 4.95,
    reviewsCount: 22,
    completedSwapsCount: 18,
    joinDate: 'Dec 2023',
    isVerified: true,
    skillsOffered: [
      {
        id: 'sk-ch-1',
        name: 'SQL',
        category: 'Programming & Tech',
        level: 'Expert',
        yearsOfExperience: 6,
        description: 'Complex CTEs, window functions, query plan analysis, indexing strategies.',
        tags: ['SQL', 'Query Optimization', 'Indexes'],
        endorsements: 45,
      },
      {
        id: 'sk-ch-2',
        name: 'Postgres',
        category: 'Programming & Tech',
        level: 'Expert',
        yearsOfExperience: 6,
        description: 'Postgres RLS, GIN/GiST indexes, JSONB operators, and stored procedures.',
        tags: ['Postgres', 'RLS', 'GIN Indexes'],
        endorsements: 38,
      },
      {
        id: 'sk-ch-3',
        name: 'Data Analysis',
        category: 'Programming & Tech',
        level: 'Advanced',
        yearsOfExperience: 5,
        description: 'Cohort analysis, retention models, funnel metrics, and statistical breakdowns.',
        tags: ['Analytics', 'Data', 'Statistics'],
        endorsements: 29,
      },
    ],
    skillsWanted: [
      {
        id: 'w-ch-1',
        name: 'React',
        category: 'Programming & Tech',
        targetLevel: 'Beginner',
        learningGoal: 'Learn component lifecycle, state hooks, and charting library integration.',
        priority: 'High',
      },
    ],
    availability: [
      { id: 'av-ch-1', day: 'Tue', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-ch-2', day: 'Sat', times: ['Morning', 'Afternoon'], preferredFormat: 'Video Call' },
    ],
    preferredFormats: ['Video Call', 'Code / Design Review'],
    privacy: {
      isProfilePublic: true,
      showEmail: false,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [],
  },
  {
    id: 'u-elena',
    name: 'Elena Rostova',
    username: 'elena_design',
    email: 'elena@skillswap.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'user',
    headline: 'Senior Product Designer • Design System & 3D Specialist',
    bio: 'Lead product designer with 7+ years designing scalable web & mobile systems. Looking to learn Rust for systems programming and deepen my Japanese conversational fluency before a Tokyo residency!',
    location: 'Berlin, Germany',
    timezone: 'UTC+1 (CET)',
    rating: 4.95,
    reviewsCount: 28,
    completedSwapsCount: 24,
    joinDate: 'Jan 2024',
    isVerified: true,
    skillsOffered: [
      {
        id: 'sk-1',
        name: 'Figma Design Systems & Auto Layout',
        category: 'Design & Creative',
        level: 'Expert',
        yearsOfExperience: 6,
        description: 'Component architecture, tokens, nested variants, accessible typography, and dev handoff specs.',
        tags: ['Figma', 'Design Systems', 'UI/UX', 'Accessibility'],
        endorsements: 34,
      },
      {
        id: 'sk-2',
        name: '3D Blender Prototyping & Lighting',
        category: 'Design & Creative',
        level: 'Intermediate',
        yearsOfExperience: 3,
        description: 'Hard-surface modeling, realistic glass/metal shaders, lighting setups for product renders.',
        tags: ['Blender', '3D', 'Cycles', 'Rendering'],
        endorsements: 16,
      },
      {
        id: 'sk-3',
        name: 'Frontend Micro-interactions (CSS & Framer Motion)',
        category: 'Programming & Tech',
        level: 'Intermediate',
        yearsOfExperience: 4,
        description: 'Smooth spring animations, exit transitions, gestures, and layout morphing.',
        tags: ['CSS', 'Motion', 'React', 'Tailwind'],
        endorsements: 21,
      },
    ],
    skillsWanted: [
      {
        id: 'w-1',
        name: 'Rust Systems Programming',
        category: 'Programming & Tech',
        targetLevel: 'Intermediate',
        learningGoal: 'Master memory safety, ownership, borrow checker, and build a high-performance CLI tool.',
        priority: 'High',
      },
      {
        id: 'w-2',
        name: 'Japanese Conversational & Kanji',
        category: 'Languages & Culture',
        targetLevel: 'Intermediate',
        learningGoal: 'Practice speaking natural everyday conversational Japanese (JLPT N3 level).',
        priority: 'Medium',
      },
      {
        id: 'w-3',
        name: 'Specialty Coffee Pour-Over Craft',
        category: 'Culinary & Crafts',
        targetLevel: 'Beginner',
        learningGoal: 'V60 water temperature dialing, grind consistency, and extraction ratios.',
        priority: 'Low',
      },
    ],
    availability: [
      { id: 'av-1', day: 'Tue', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-2', day: 'Thu', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-3', day: 'Sat', times: ['Morning', 'Afternoon'], preferredFormat: 'Live Chat' },
      { id: 'av-4', day: 'Sun', times: ['Morning'], preferredFormat: 'Code / Design Review' },
    ],
    preferredFormats: ['Video Call', 'Code / Design Review'],
    privacy: {
      isProfilePublic: true,
      showEmail: false,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [
      {
        id: 'rev-1',
        swapId: 'sw-101',
        reviewerId: 'u-marcus',
        reviewerName: 'Marcus Vance',
        reviewerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        skillExchanged: 'Figma Design Systems',
        comment: 'Elena is an absolute master of Figma tokens! She completely transformed how I structure frontend component variants. Extremely patient and provided incredible reference templates.',
        date: '3 days ago',
        punctualityScore: 5,
        clarityScore: 5,
        badges: ['Top Mentor', 'Ultra Clear', 'Resourceful'],
      },
      {
        id: 'rev-2',
        swapId: 'sw-102',
        reviewerId: 'u-aoi',
        reviewerName: 'Aoi Tanaka',
        reviewerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        skillExchanged: '3D Blender Prototyping',
        comment: 'Incredible session! Elena taught me lighting techniques in Blender that immediately leveled up my indie game assets. Looking forward to our next swap!',
        date: '2 weeks ago',
        punctualityScore: 5,
        clarityScore: 5,
        badges: ['Inspiring', 'Hands-on'],
      },
    ],
  },
  {
    id: 'u-marcus',
    name: 'Marcus Vance',
    username: 'marcus_dev',
    email: 'marcus@skillswap.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'user',
    headline: 'Distributed Systems & Rust Core Engineer • Cloud Architect',
    bio: 'Backend tech lead building high-concurrency microservices. Rust enthusiast, Kubernetes certified. Seeking to level up my UI visual design intuition and audio mixing skills!',
    location: 'Austin, TX, USA',
    timezone: 'UTC-5 (CDT)',
    rating: 4.98,
    reviewsCount: 31,
    completedSwapsCount: 29,
    joinDate: 'Oct 2023',
    isVerified: true,
    skillsOffered: [
      {
        id: 'sk-4',
        name: 'Rust Systems Programming & Async Tokio',
        category: 'Programming & Tech',
        level: 'Expert',
        yearsOfExperience: 5,
        description: 'Memory safety, zero-cost abstractions, multithreading, concurrency patterns, and microservice backends.',
        tags: ['Rust', 'Tokio', 'Systems', 'Performance', 'Backend'],
        endorsements: 48,
      },
      {
        id: 'sk-5',
        name: 'Docker, Kubernetes & Cloud Native Infra',
        category: 'Programming & Tech',
        level: 'Expert',
        yearsOfExperience: 7,
        description: 'Cluster orchestration, Helm charts, CI/CD pipelines, observability with Prometheus/Grafana.',
        tags: ['Kubernetes', 'Docker', 'DevOps', 'AWS', 'GCP'],
        endorsements: 39,
      },
      {
        id: 'sk-6',
        name: 'PostgreSQL Database Performance Tuning',
        category: 'Programming & Tech',
        level: 'Advanced',
        yearsOfExperience: 6,
        description: 'Index optimization, query analysis with EXPLAIN ANALYZE, vacuum tuning, partition tables.',
        tags: ['PostgreSQL', 'Database', 'SQL', 'Optimization'],
        endorsements: 27,
      },
    ],
    skillsWanted: [
      {
        id: 'w-4',
        name: 'Figma UI/UX & Design Systems',
        category: 'Design & Creative',
        targetLevel: 'Intermediate',
        learningGoal: 'Design intuitive developer tooling interfaces and clean dashboards without relying on defaults.',
        priority: 'High',
      },
      {
        id: 'w-5',
        name: 'Ableton Live Electronic Music Production',
        category: 'Music & Audio',
        targetLevel: 'Beginner',
        learningGoal: 'Learn synth sound design (Wavetable/Serum), drum programming, and basic song arrangement.',
        priority: 'Medium',
      },
      {
        id: 'w-6',
        name: 'Spanish Conversational',
        category: 'Languages & Culture',
        targetLevel: 'Beginner',
        learningGoal: 'Basic conversational phrases and pronunciation for upcoming trip to Mexico.',
        priority: 'Low',
      },
    ],
    availability: [
      { id: 'av-5', day: 'Mon', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-6', day: 'Wed', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-7', day: 'Sat', times: ['Morning', 'Afternoon'], preferredFormat: 'Code / Design Review' },
    ],
    preferredFormats: ['Video Call', 'Code / Design Review', 'Live Chat'],
    privacy: {
      isProfilePublic: true,
      showEmail: false,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [
      {
        id: 'rev-3',
        swapId: 'sw-101',
        reviewerId: 'u-elena',
        reviewerName: 'Elena Rostova',
        reviewerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        skillExchanged: 'Rust Systems Programming',
        comment: 'Marcus made Rust concepts like Lifetimes and the Borrow Checker feel intuitive with clear visual analogies. Highly recommended mentor!',
        date: '1 week ago',
        punctualityScore: 5,
        clarityScore: 5,
        badges: ['Genius Explainer', 'Patient', 'Practical'],
      },
    ],
  },
  {
    id: 'u-aoi',
    name: 'Aoi Tanaka',
    username: 'aoi_sound',
    email: 'aoi@skillswap.io',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'user',
    headline: 'Native Japanese Instructor & Electronic Music Producer',
    bio: 'Tokyo-born sound designer and certified Japanese language educator. I love helping peers break past pronunciation hurdles and explore ambient sound synthesis!',
    location: 'Kyoto, Japan',
    timezone: 'UTC+9 (JST)',
    rating: 5.0,
    reviewsCount: 42,
    completedSwapsCount: 38,
    joinDate: 'Jul 2023',
    isVerified: true,
    skillsOffered: [
      {
        id: 'sk-7',
        name: 'Native Japanese Language & Pronunciation (All Levels)',
        category: 'Languages & Culture',
        level: 'Expert',
        yearsOfExperience: 8,
        description: 'Nuanced conversational Japanese, business honorifics (Keigo), anime/manga colloquialisms, JLPT prep.',
        tags: ['Japanese', 'Language', 'Pronunciation', 'JLPT', 'Culture'],
        endorsements: 62,
      },
      {
        id: 'sk-8',
        name: 'Ableton Live Electronic Music Production & Sound Design',
        category: 'Music & Audio',
        level: 'Advanced',
        yearsOfExperience: 6,
        description: 'Synth patching, sampling workflow, ambient reverb manipulation, dynamic mix balance.',
        tags: ['Ableton', 'Sound Design', 'Music Production', 'Synthesizers'],
        endorsements: 31,
      },
    ],
    skillsWanted: [
      {
        id: 'w-7',
        name: 'React & TypeScript Web Apps',
        category: 'Programming & Tech',
        targetLevel: 'Intermediate',
        learningGoal: 'Build an interactive web-based synthesizer and portfolio website.',
        priority: 'High',
      },
      {
        id: 'w-8',
        name: '3D Blender Asset Modeling',
        category: 'Design & Creative',
        targetLevel: 'Beginner',
        learningGoal: 'Create low-poly 3D visualizers for live music streaming performances.',
        priority: 'Medium',
      },
    ],
    availability: [
      { id: 'av-8', day: 'Tue', times: ['Morning', 'Evening'], preferredFormat: 'Video Call' },
      { id: 'av-9', day: 'Fri', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-10', day: 'Sun', times: ['Afternoon', 'Evening'], preferredFormat: 'Live Chat' },
    ],
    preferredFormats: ['Video Call', 'Live Chat'],
    privacy: {
      isProfilePublic: true,
      showEmail: false,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [
      {
        id: 'rev-4',
        swapId: 'sw-103',
        reviewerId: 'u-diego',
        reviewerName: 'Diego Ramirez',
        reviewerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        skillExchanged: 'Native Japanese Language',
        comment: 'Aoi gave me the exact phonetic breakdown I needed to sound natural. Her custom flashcards and dialogue exercises made every minute super fun.',
        date: '2 weeks ago',
        punctualityScore: 5,
        clarityScore: 5,
        badges: ['Super Engaging', 'Great Materials', 'Friendly'],
      },
    ],
  },
  {
    id: 'u-diego',
    name: 'Diego Ramirez',
    username: 'diego_culinary',
    email: 'diego@skillswap.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'user',
    headline: 'Pastry Chef, Sourdough Baker & Native Spanish Speaker',
    bio: 'Artisan bakery owner in Madrid. Passionate about sourdough fermentation chemistry, wild yeast starters, and authentic regional Spanish cooking. Eager to master Python for inventory automation!',
    location: 'Madrid, Spain',
    timezone: 'UTC+1 (CET)',
    rating: 4.92,
    reviewsCount: 19,
    completedSwapsCount: 17,
    joinDate: 'Nov 2023',
    isVerified: true,
    skillsOffered: [
      {
        id: 'sk-9',
        name: 'Artisan Sourdough & Wild Yeast Fermentation',
        category: 'Culinary & Crafts',
        level: 'Expert',
        yearsOfExperience: 9,
        description: 'Hydration math, levain management, bulk fermentation timing, Dutch oven scoring techniques.',
        tags: ['Sourdough', 'Baking', 'Fermentation', 'Bread', 'Culinary'],
        endorsements: 41,
      },
      {
        id: 'sk-10',
        name: 'Native Spanish (Castilian & Latin American)',
        category: 'Languages & Culture',
        level: 'Expert',
        yearsOfExperience: 10,
        description: 'Conversational fluency, grammar mastery, cultural idioms, writing reviews and articles.',
        tags: ['Spanish', 'Language', 'Culture', 'Grammar'],
        endorsements: 29,
      },
    ],
    skillsWanted: [
      {
        id: 'w-9',
        name: 'Python & Data Automation',
        category: 'Programming & Tech',
        targetLevel: 'Intermediate',
        learningGoal: 'Automate bakery ingredient inventory, order predictions, and sales CSV reporting with pandas.',
        priority: 'High',
      },
      {
        id: 'w-10',
        name: 'Technical SEO & Local Business Growth',
        category: 'Business & Growth',
        targetLevel: 'Beginner',
        learningGoal: 'Boost Google Maps ranking and optimize online ordering store.',
        priority: 'Medium',
      },
    ],
    availability: [
      { id: 'av-11', day: 'Mon', times: ['Afternoon'], preferredFormat: 'Video Call' },
      { id: 'av-12', day: 'Wed', times: ['Afternoon'], preferredFormat: 'Video Call' },
      { id: 'av-13', day: 'Sun', times: ['Morning', 'Evening'], preferredFormat: 'Live Chat' },
    ],
    preferredFormats: ['Video Call', 'Live Chat'],
    privacy: {
      isProfilePublic: true,
      showEmail: false,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [
      {
        id: 'rev-5',
        swapId: 'sw-104',
        reviewerId: 'u-elena',
        reviewerName: 'Elena Rostova',
        reviewerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        skillExchanged: 'Artisan Sourdough',
        comment: 'My loaves went from flat bricks to open, airy crumb after just two sessions with Diego. He demystified hydration calculations completely!',
        date: '3 weeks ago',
        punctualityScore: 5,
        clarityScore: 5,
        badges: ['Chef Master', 'Super Clear'],
      },
    ],
  },
  {
    id: 'u-priya',
    name: 'Priya Sharma',
    username: 'priya_growth',
    email: 'priya@skillswap.io',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'user',
    headline: 'Growth Marketing Lead & Vinyasa Yoga Teacher',
    bio: 'Product growth strategist helping startups scale from 0 to 1M users. Certified 500-hr yoga instructor. Wanting to learn acoustic guitar and Spanish!',
    location: 'San Francisco, CA, USA',
    timezone: 'UTC-8 (PST)',
    rating: 4.88,
    reviewsCount: 15,
    completedSwapsCount: 13,
    joinDate: 'Feb 2024',
    isVerified: true,
    skillsOffered: [
      {
        id: 'sk-11',
        name: 'Startup Growth Strategy & Conversion Funnels',
        category: 'Business & Growth',
        level: 'Expert',
        yearsOfExperience: 7,
        description: 'Landing page CRO, user onboarding friction audits, viral loops, organic attribution tracking.',
        tags: ['Growth', 'Marketing', 'CRO', 'Startups', 'Product'],
        endorsements: 33,
      },
      {
        id: 'sk-12',
        name: 'Vinyasa Yoga & Breathwork for Desk Workers',
        category: 'Health & Fitness',
        level: 'Advanced',
        yearsOfExperience: 6,
        description: 'Postural correction for engineers, hip mobility sequences, guided box-breathing to relieve stress.',
        tags: ['Yoga', 'Mobility', 'Mindfulness', 'Fitness', 'Wellness'],
        endorsements: 25,
      },
    ],
    skillsWanted: [
      {
        id: 'w-11',
        name: 'Acoustic Guitar Fingerpicking',
        category: 'Music & Audio',
        targetLevel: 'Beginner',
        learningGoal: 'Learn open chord transitions, rhythm strumming, and fingerstyle patterns.',
        priority: 'High',
      },
      {
        id: 'w-12',
        name: 'Spanish Conversational',
        category: 'Languages & Culture',
        targetLevel: 'Beginner',
        learningGoal: 'Basic travel dialogue and grammar fundamentals.',
        priority: 'Medium',
      },
    ],
    availability: [
      { id: 'av-14', day: 'Tue', times: ['Morning'], preferredFormat: 'Video Call' },
      { id: 'av-15', day: 'Thu', times: ['Morning'], preferredFormat: 'Video Call' },
      { id: 'av-16', day: 'Sat', times: ['Morning', 'Afternoon'], preferredFormat: 'Video Call' },
    ],
    preferredFormats: ['Video Call', 'Live Chat'],
    privacy: {
      isProfilePublic: true,
      showEmail: false,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [],
  },
  {
    id: 'u-alex-admin',
    name: 'Alex Mercer (Admin)',
    username: 'alex_admin',
    email: 'admin@skillswap.io',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    role: 'admin',
    headline: 'SkillSwap Platform Director & Community Trustee',
    bio: 'Platform architect maintaining community standards, reviewing reported skill disputes, and ensuring fair, productive peer knowledge exchanges.',
    location: 'Stockholm, Sweden',
    timezone: 'UTC+1 (CET)',
    rating: 5.0,
    reviewsCount: 50,
    completedSwapsCount: 45,
    joinDate: 'Jan 2023',
    isVerified: true,
    skillsOffered: [
      {
        id: 'sk-13',
        name: 'Full-Stack Architecture & TypeScript',
        category: 'Programming & Tech',
        level: 'Expert',
        yearsOfExperience: 10,
        description: 'End-to-end architecture, API contracts, WebSocket real-time hubs, React 19 best practices.',
        tags: ['TypeScript', 'Architecture', 'React', 'Node.js'],
        endorsements: 75,
      },
    ],
    skillsWanted: [
      {
        id: 'w-13',
        name: 'Classical Piano Sight-Reading',
        category: 'Music & Audio',
        targetLevel: 'Intermediate',
        learningGoal: 'Chopin Nocturnes and complex chord sight reading.',
        priority: 'Medium',
      },
    ],
    availability: [
      { id: 'av-17', day: 'Fri', times: ['Afternoon', 'Evening'], preferredFormat: 'Video Call' },
      { id: 'av-18', day: 'Sun', times: ['Morning'], preferredFormat: 'Live Chat' },
    ],
    preferredFormats: ['Video Call', 'Code / Design Review'],
    privacy: {
      isProfilePublic: true,
      showEmail: true,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [],
  },
];

export const INITIAL_SWAP_REQUESTS: SwapRequest[] = [
  {
    id: 'swap-active-1',
    senderId: 'u-marcus',
    senderName: 'Marcus Vance',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    senderHeadline: 'Distributed Systems & Rust Core Engineer',
    receiverId: 'u-elena',
    receiverName: 'Elena Rostova',
    receiverAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    receiverHeadline: 'Senior Product Designer • Design System Specialist',
    offeredSkill: {
      name: 'Rust Systems Programming & Async Tokio',
      level: 'Expert',
      category: 'Programming & Tech',
    },
    requestedSkill: {
      name: 'Figma Design Systems & Auto Layout',
      level: 'Expert',
      category: 'Design & Creative',
    },
    status: 'in_progress',
    sessionFormat: 'Video Call',
    proposedSchedule: 'Tuesdays & Thursdays at 18:00 CET',
    initialMessage: 'Hey Elena! I loved your article on design tokens. I would love to do a 4-session exchange: I will guide you through Rust async memory models & Tokio CLI dev in return for hands-on Figma component library structuring for my developer dashboard!',
    createdAt: '2 days ago',
    updatedAt: '1 hour ago',
    meetingLink: 'https://meet.skillswap.io/room-elena-marcus-948',
    sharedNotes: `### Mutual Learning Goals
1. **Elena's Goal**: Implement a high-speed CLI file watcher in Rust using \`notify\` and \`tokio\`.
2. **Marcus's Goal**: Build a dark-mode token palette and dynamic button variant component with auto-layout in Figma.

### Recommended Readings & Files
- Rust Book chapters on Ownership and Traits
- Figma Design Tokens community template`,
    objectives: [
      { id: 'obj-1', text: 'Marcus walks Elena through Rust Ownership, Borrow Checker, and Struct traits', completed: true },
      { id: 'obj-2', text: 'Elena guides Marcus through creating modular Figma Auto-Layout containers & variants', completed: true },
      { id: 'obj-3', text: 'Elena pairs on Rust Tokio Async channel buffering and error handling', completed: false },
      { id: 'obj-4', text: 'Elena audits Marcus\'s Figma component architecture and typography scale', completed: false },
    ],
    messages: [
      {
        id: 'm-1',
        senderId: 'u-marcus',
        senderName: 'Marcus Vance',
        senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        text: 'Hi Elena! Thanks for accepting the swap. I pre-configured our code sandbox and drafted our 4 session milestones above.',
        timestamp: 'Yesterday at 14:20',
      },
      {
        id: 'm-2',
        senderId: 'u-elena',
        senderName: 'Elena Rostova',
        senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        text: 'Awesome! I prepared a starter Figma playground file with token variables so you can jump right into component nesting during our Thursday call.',
        timestamp: 'Yesterday at 15:05',
      },
      {
        id: 'm-3',
        senderId: 'u-marcus',
        senderName: 'Marcus Vance',
        senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        text: 'Perfect. Looking forward to Thursday at 18:00 CET! Let me know if you want to test the meeting link beforehand.',
        timestamp: '1 hour ago',
      },
    ],
  },
  {
    id: 'swap-pending-1',
    senderId: 'u-aoi',
    senderName: 'Aoi Tanaka',
    senderAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    senderHeadline: 'Native Japanese Instructor & Electronic Music Producer',
    receiverId: 'u-elena',
    receiverName: 'Elena Rostova',
    receiverAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    receiverHeadline: 'Senior Product Designer • Design System Specialist',
    offeredSkill: {
      name: 'Native Japanese Language & Pronunciation (All Levels)',
      level: 'Expert',
      category: 'Languages & Culture',
    },
    requestedSkill: {
      name: '3D Blender Prototyping & Lighting',
      level: 'Intermediate',
      category: 'Design & Creative',
    },
    status: 'pending',
    sessionFormat: 'Video Call',
    proposedSchedule: 'Sundays at 14:00 CET / 22:00 JST',
    initialMessage: 'Konnichiwa Elena! I noticed you are planning a residency in Tokyo and want Japanese conversation practice! I would love to practice conversational Japanese with you (focusing on design studio terminology & daily life) in exchange for 3D Blender lighting techniques for my live stream visuals!',
    createdAt: '4 hours ago',
    updatedAt: '4 hours ago',
    objectives: [],
    messages: [],
  },
  {
    id: 'swap-incoming-diego',
    senderId: 'u-diego',
    senderName: 'Diego Ramirez',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    senderHeadline: 'Pastry Chef, Sourdough Baker & Native Spanish Speaker',
    receiverId: 'u-marcus',
    receiverName: 'Marcus Vance',
    receiverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    receiverHeadline: 'Distributed Systems & Rust Core Engineer',
    offeredSkill: {
      name: 'Artisan Sourdough & Wild Yeast Fermentation',
      level: 'Expert',
      category: 'Culinary & Crafts',
    },
    requestedSkill: {
      name: 'PostgreSQL Database Performance Tuning',
      level: 'Advanced',
      category: 'Programming & Tech',
    },
    status: 'pending',
    sessionFormat: 'Video Call',
    proposedSchedule: 'Wednesday afternoons',
    initialMessage: 'Hola Marcus! I run an artisan bakery and need help optimizing our Postgres inventory schema queries so our checkout is instant. I can teach you the foolproof chemistry of 80% hydration artisan sourdough loaves and woodfired focaccia!',
    createdAt: 'Yesterday',
    updatedAt: 'Yesterday',
    objectives: [],
    messages: [],
  },
  {
    id: 'swap-completed-1',
    senderId: 'u-priya',
    senderName: 'Priya Sharma',
    senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    senderHeadline: 'Growth Marketing Lead & Vinyasa Yoga Teacher',
    receiverId: 'u-elena',
    receiverName: 'Elena Rostova',
    receiverAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    receiverHeadline: 'Senior Product Designer • Design System Specialist',
    offeredSkill: {
      name: 'Vinyasa Yoga & Breathwork for Desk Workers',
      level: 'Advanced',
      category: 'Health & Fitness',
    },
    requestedSkill: {
      name: 'Frontend Micro-interactions (CSS & Framer Motion)',
      level: 'Intermediate',
      category: 'Programming & Tech',
    },
    status: 'completed',
    sessionFormat: 'Video Call',
    proposedSchedule: 'Weekend mornings',
    initialMessage: 'Hi Elena! Let\'s swap desk yoga routines for Framer Motion animation tutorials for my newsletter page!',
    createdAt: '2 weeks ago',
    updatedAt: '5 days ago',
    senderReviewSubmitted: true,
    receiverReviewSubmitted: true,
    objectives: [
      { id: 'o-1', text: 'Yoga session for thoracic spine and neck posture', completed: true },
      { id: 'o-2', text: 'Framer Motion page transition and hover spring physics', completed: true },
    ],
    messages: [
      {
        id: 'm-c1',
        senderId: 'u-priya',
        senderName: 'Priya Sharma',
        senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        text: 'Elena, thank you so much for the animation coaching! The smooth springs look so sleek on my landing page.',
        timestamp: '5 days ago',
      },
    ],
  },
];

export const INITIAL_REPORTS: AdminReport[] = [
  {
    id: 'rep-1',
    reporterId: 'u-diego',
    reporterName: 'Diego Ramirez',
    targetType: 'user',
    targetId: 'u-spam-bot',
    targetName: 'CryptoSignals_Daily',
    reason: 'Spamming commercial crypto promotions in swap requests instead of genuine skill learning.',
    details: 'User sent 5 swap proposals offering "100x Crypto Signals" and asking for private WhatsApp numbers.',
    status: 'pending',
    createdAt: '3 hours ago',
  },
  {
    id: 'rep-2',
    reporterId: 'u-aoi',
    reporterName: 'Aoi Tanaka',
    targetType: 'swap',
    targetId: 'swap-dispute-99',
    targetName: 'Swap with User #4810 (Ghosted Session)',
    reason: 'Partner did not show up for scheduled 1-on-1 swap without advance notification twice.',
    details: 'We agreed to meet on Zoom Sunday at 14:00. Partner missed both confirmed slots with zero response.',
    status: 'pending',
    createdAt: '1 day ago',
  },
];

export const INITIAL_ANNOUNCEMENTS: PlatformAnnouncement[] = [
  {
    id: 'ann-1',
    title: '🎉 Spring Community Skill Sprint is Live!',
    content: 'Complete at least 2 verified skill swaps this month to earn the "Master Peer Exchanger" badge and unlock early access to group workshops.',
    type: 'event',
    isActive: true,
    date: 'Aug 28, 2026',
    author: 'Alex Mercer (Platform Director)',
  },
  {
    id: 'ann-2',
    title: '🔒 Enhanced Privacy Controls Released',
    content: 'You can now configure who can view your email, approximate location, and choose to accept swap proposals only from members with verified 4.8+ ratings.',
    type: 'feature',
    isActive: true,
    date: 'Aug 20, 2026',
    author: 'Alex Mercer (Platform Director)',
  },
];

export const INITIAL_NOTIFICATIONS: PlatformNotification[] = [
  {
    id: 'notif-1',
    userId: 'u-elena',
    title: 'New Skill Swap Request!',
    message: 'Aoi Tanaka proposed a swap: Japanese Language for 3D Blender Prototyping.',
    type: 'swap_request',
    createdAt: '4 hours ago',
    read: false,
    swapId: 'swap-pending-1',
  },
  {
    id: 'notif-2',
    userId: 'u-elena',
    title: 'Active Session Reminder',
    message: 'Upcoming session with Marcus Vance tomorrow at 18:00 CET.',
    type: 'swap_accepted',
    createdAt: 'Yesterday',
    read: false,
    swapId: 'swap-active-1',
  },
  {
    id: 'notif-3',
    userId: 'u-elena',
    title: 'Review Received ⭐️⭐️⭐️⭐️⭐️',
    message: 'Marcus Vance gave you a 5-star review for Figma Design Systems.',
    type: 'review_received',
    createdAt: '3 days ago',
    read: true,
  },
];

export const INITIAL_SWAPS = INITIAL_SWAP_REQUESTS;
