import { 
  UserProfile, 
  SwapRequest, 
  SkillCategoryDefinition, 
  AdminReport, 
  PlatformAnnouncement,
  PlatformNotification
} from './types';

export const SKILL_CATEGORIES: SkillCategoryDefinition[] = [
  {
    id: 'design',
    name: 'Design & Creative',
    description: 'UI/UX Design, Figma, Photoshop, 3D & Branding',
    iconName: 'Palette',
    popularSkills: ['Figma', 'Photoshop', 'UI/UX', '3D Blender', 'Graphic Design'],
    colorTheme: 'from-purple-500/10 to-pink-500/10 border-purple-500/20 text-purple-600',
  },
  {
    id: 'tech',
    name: 'Programming & Tech',
    description: 'Python, React, Node.js, SQL, PostgreSQL & Web Dev',
    iconName: 'Code',
    popularSkills: ['Python', 'React', 'Node.js', 'SQL', 'Postgres', 'Data Analysis'],
    colorTheme: 'from-blue-500/10 to-indigo-500/10 border-blue-500/20 text-blue-600',
  },
  {
    id: 'languages',
    name: 'Languages & Culture',
    description: 'Conversational Fluency, Grammar, Accent & Culture',
    iconName: 'Globe',
    popularSkills: ['Spanish', 'Japanese', 'French', 'German', 'Mandarin'],
    colorTheme: 'from-emerald-500/10 to-teal-500/10 border-emerald-500/20 text-emerald-600',
  },
  {
    id: 'music',
    name: 'Music & Audio',
    description: 'Guitar, Music Production, Piano, Sound Design & Mixing',
    iconName: 'Music',
    popularSkills: ['Ableton Live', 'Acoustic Guitar', 'Piano', 'Audio Mixing'],
    colorTheme: 'from-amber-500/10 to-orange-500/10 border-amber-500/20 text-amber-600',
  },
  {
    id: 'business',
    name: 'Business & Growth',
    description: 'Product Management, SEO, Startup Pitching, Analytics',
    iconName: 'TrendingUp',
    popularSkills: ['Product Strategy', 'Technical SEO', 'Pitch Decks', 'Data Analysis'],
    colorTheme: 'from-cyan-500/10 to-blue-500/10 border-cyan-500/20 text-cyan-600',
  },
  {
    id: 'culinary',
    name: 'Culinary & Crafts',
    description: 'Baking, Coffee Brewing, Woodworking, Pottery',
    iconName: 'Utensils',
    popularSkills: ['Sourdough Baking', 'Espresso Craft', 'Pottery', 'Cooking'],
    colorTheme: 'from-rose-500/10 to-pink-500/10 border-rose-500/20 text-rose-600',
  },
  {
    id: 'health',
    name: 'Health & Fitness',
    description: 'Yoga, Marathon Training, Nutrition, Strength',
    iconName: 'HeartPulse',
    popularSkills: ['Vinyasa Yoga', 'Marathon Prep', 'Nutrition', 'Mobility'],
    colorTheme: 'from-lime-500/10 to-green-500/10 border-lime-500/20 text-lime-600',
  },
  {
    id: 'academics',
    name: 'Academics & Science',
    description: 'Calculus, Statistics, Physics, Paper Review',
    iconName: 'GraduationCap',
    popularSkills: ['Statistics', 'Calculus', 'Data Science', 'Academic Writing'],
    colorTheme: 'from-indigo-500/10 to-violet-500/10 border-indigo-500/20 text-indigo-600',
  },
];

// Exact Database Profiles from Supabase (dummy-data.sql)
export const INITIAL_USERS: UserProfile[] = [
  {
    id: '47e26eab-001b-4c40-a6fc-93899018d6c2',
    name: 'Alice Designer',
    username: 'alice_designer',
    email: 'alice@hackathon.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'admin',
    headline: 'Senior UI/UX Designer & Design System Lead (Platform Admin)',
    bio: 'Figma and Photoshop specialist with passion for design systems, accessible UI, and micro-interactions. Looking to expand into Python backend servers and SQL databases!',
    location: 'New York, USA',
    timezone: 'UTC-5 (EST)',
    rating: 5.0,
    reviewsCount: 1,
    completedSwapsCount: 1,
    joinDate: 'Aug 2026',
    isVerified: true,
    isBanned: false,
    skillsOffered: [
      {
        id: 'sk-al-1',
        name: 'Figma',
        category: 'Design & Creative',
        level: 'Expert',
        yearsOfExperience: 6,
        description: 'Auto layout, design tokens, nested components, and interactive prototypes.',
        tags: ['Figma', 'UI/UX', 'Design Systems'],
        endorsements: 42,
      },
      {
        id: 'sk-al-2',
        name: 'Photoshop',
        category: 'Design & Creative',
        level: 'Advanced',
        yearsOfExperience: 5,
        description: 'Photo retouching, banner composition, and visual brand assets.',
        tags: ['Photoshop', 'Branding', 'Graphics'],
        endorsements: 28,
      },
      {
        id: 'sk-al-3',
        name: 'UI/UX',
        category: 'Design & Creative',
        level: 'Expert',
        yearsOfExperience: 7,
        description: 'User flows, wireframing, usability heuristics, and user research.',
        tags: ['UI/UX', 'Wireframes', 'Research'],
        endorsements: 36,
      },
    ],
    skillsWanted: [
      {
        id: 'w-al-1',
        name: 'Python',
        category: 'Programming & Tech',
        targetLevel: 'Intermediate',
        learningGoal: 'Build backend APIs with FastAPI / Flask and script automated design asset generators.',
        priority: 'High',
      },
      {
        id: 'w-al-2',
        name: 'SQL',
        category: 'Programming & Tech',
        targetLevel: 'Beginner',
        learningGoal: 'Master PostgreSQL querying, joins, and data schemas.',
        priority: 'Medium',
      },
    ],
    availability: [
      { id: 'av-al-1', day: 'Sat', times: ['Morning', 'Afternoon'], preferredFormat: 'Video Call' },
      { id: 'av-al-2', day: 'Sun', times: ['Morning', 'Afternoon'], preferredFormat: 'Code / Design Review' },
    ],
    preferredFormats: ['Video Call', 'Code / Design Review'],
    privacy: {
      isProfilePublic: true,
      showEmail: true,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [
      {
        id: 'dba239eb-a27b-4bdf-ac99-ef2c035c1a6b',
        swapId: 'swap-demo-1',
        reviewerId: 'cf27f01d-10c3-4cdd-b3e4-0a9e61699c00',
        reviewerName: 'Charlie Data',
        reviewerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        rating: 5,
        skillExchanged: 'Figma & UI/UX Design',
        comment: 'Alice is an incredible designer! Highly recommend swapping skills with her.',
        date: 'Recently',
        punctualityScore: 5,
        clarityScore: 5,
        badges: ['Super Clear', 'Creative Genius', 'Patient Mentor'],
      },
    ],
  },
  {
    id: '7b3dcfd5-7b66-4c31-b592-b0f980bb77a3',
    name: 'Bob The Dev',
    username: 'bob_dev',
    email: 'bob@hackathon.com',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    role: 'user',
    headline: 'Full-Stack Developer • Python, React & Node.js Engineer',
    bio: 'Software engineer building web apps and cloud APIs. Happy to teach Python and React in exchange for Figma UI design secrets and advanced CSS animation techniques!',
    location: 'London, UK',
    timezone: 'UTC+0 (GMT)',
    rating: 4.9,
    reviewsCount: 4,
    completedSwapsCount: 3,
    joinDate: 'Aug 2026',
    isVerified: true,
    isBanned: false,
    skillsOffered: [
      {
        id: 'sk-bob-1',
        name: 'Python',
        category: 'Programming & Tech',
        level: 'Expert',
        yearsOfExperience: 5,
        description: 'Backend services, async programming, data processing, and automation scripts.',
        tags: ['Python', 'FastAPI', 'Backend'],
        endorsements: 31,
      },
      {
        id: 'sk-bob-2',
        name: 'React',
        category: 'Programming & Tech',
        level: 'Advanced',
        yearsOfExperience: 4,
        description: 'Modern React 19, hooks, custom state management, and performance tuning.',
        tags: ['React', 'TypeScript', 'Frontend'],
        endorsements: 27,
      },
      {
        id: 'sk-bob-3',
        name: 'Node.js',
        category: 'Programming & Tech',
        level: 'Advanced',
        yearsOfExperience: 4,
        description: 'RESTful APIs, middleware architecture, Express and authentication.',
        tags: ['Node.js', 'Express', 'APIs'],
        endorsements: 22,
      },
    ],
    skillsWanted: [
      {
        id: 'w-bob-1',
        name: 'Figma',
        category: 'Design & Creative',
        targetLevel: 'Intermediate',
        learningGoal: 'Design realistic mockups and learn Auto Layout for fast prototyping.',
        priority: 'High',
      },
      {
        id: 'w-bob-2',
        name: 'CSS',
        category: 'Programming & Tech',
        targetLevel: 'Advanced',
        learningGoal: 'Master CSS grid, subgrid, container queries, and glassmorphism styling.',
        priority: 'Medium',
      },
    ],
    availability: [
      { id: 'av-bob-1', day: 'Mon', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-bob-2', day: 'Wed', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-bob-3', day: 'Fri', times: ['Evening'], preferredFormat: 'Live Chat' },
    ],
    preferredFormats: ['Video Call', 'Live Chat'],
    privacy: {
      isProfilePublic: true,
      showEmail: false,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [],
  },
  {
    id: 'cf27f01d-10c3-4cdd-b3e4-0a9e61699c00',
    name: 'Charlie Data',
    username: 'charlie_data',
    email: 'charlie@hackathon.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'user',
    headline: 'Data Engineer & SQL Expert • Postgres Performance Tuning',
    bio: 'Database specialist with 6+ years optimizing Postgres queries, data pipelines, and analytics warehouses. Looking to learn React to build interactive internal analytics tools!',
    location: 'Remote, Worldwide',
    timezone: 'UTC+2 (EET)',
    rating: 4.95,
    reviewsCount: 6,
    completedSwapsCount: 5,
    joinDate: 'Aug 2026',
    isVerified: true,
    isBanned: false,
    skillsOffered: [
      {
        id: 'sk-ch-1',
        name: 'SQL',
        category: 'Programming & Tech',
        level: 'Expert',
        yearsOfExperience: 6,
        description: 'Complex CTEs, window functions, query plan analysis, indexing strategies.',
        tags: ['SQL', 'Query Optimization', 'Indexes'],
        endorsements: 45,
      },
      {
        id: 'sk-ch-2',
        name: 'Postgres',
        category: 'Programming & Tech',
        level: 'Expert',
        yearsOfExperience: 6,
        description: 'Postgres RLS, GIN/GiST indexes, JSONB operators, and stored procedures.',
        tags: ['Postgres', 'RLS', 'GIN Indexes'],
        endorsements: 38,
      },
      {
        id: 'sk-ch-3',
        name: 'Data Analysis',
        category: 'Programming & Tech',
        level: 'Advanced',
        yearsOfExperience: 5,
        description: 'Cohort analysis, retention models, funnel metrics, and statistical breakdowns.',
        tags: ['Analytics', 'Data', 'Statistics'],
        endorsements: 29,
      },
    ],
    skillsWanted: [
      {
        id: 'w-ch-1',
        name: 'React',
        category: 'Programming & Tech',
        targetLevel: 'Beginner',
        learningGoal: 'Learn component lifecycle, state hooks, and charting library integration.',
        priority: 'High',
      },
    ],
    availability: [
      { id: 'av-ch-1', day: 'Tue', times: ['Evening'], preferredFormat: 'Video Call' },
      { id: 'av-ch-2', day: 'Sat', times: ['Morning', 'Afternoon'], preferredFormat: 'Video Call' },
    ],
    preferredFormats: ['Video Call', 'Code / Design Review'],
    privacy: {
      isProfilePublic: true,
      showEmail: false,
      showLocation: true,
      allowDirectMessages: true,
      openToSwapRequests: true,
      hideCompletedSwaps: false,
    },
    reviews: [],
  },
];

export const INITIAL_SWAP_REQUESTS: SwapRequest[] = [
  {
    id: 'swap-seed-1',
    senderId: '47e26eab-001b-4c40-a6fc-93899018d6c2', // Alice
    senderName: 'Alice Designer',
    senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    senderHeadline: 'Senior UI/UX Designer & Design System Lead',
    receiverId: '7b3dcfd5-7b66-4c31-b592-b0f980bb77a3', // Bob
    receiverName: 'Bob The Dev',
    receiverAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    receiverHeadline: 'Full-Stack Developer • Python & React',
    offeredSkill: {
      name: 'Figma',
      level: 'Expert',
      category: 'Design & Creative',
    },
    requestedSkill: {
      name: 'Python',
      level: 'Expert',
      category: 'Programming & Tech',
    },
    status: 'pending',
    sessionFormat: 'Video Call',
    proposedSchedule: 'Weekends (Saturday afternoon)',
    initialMessage: 'Hey Bob! I can teach you Figma if you can help me set up a Python server.',
    createdAt: 'Recently',
    updatedAt: 'Recently',
    objectives: [
      { id: 'obj-1', text: 'Set up Python FastAPI backend structure', completed: false },
      { id: 'obj-2', text: 'Figma Auto Layout and Component variant workshop', completed: false },
    ],
    messages: [
      {
        id: 'msg-seed-1',
        senderId: '47e26eab-001b-4c40-a6fc-93899018d6c2',
        senderName: 'Alice Designer',
        senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
        text: 'Hey Bob! I can teach you Figma if you can help me set up a Python server.',
        timestamp: 'Recently',
      }
    ],
  },
  {
    id: 'swap-seed-2',
    senderId: 'cf27f01d-10c3-4cdd-b3e4-0a9e61699c00', // Charlie
    senderName: 'Charlie Data',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    senderHeadline: 'Data Engineer & SQL Expert',
    receiverId: '47e26eab-001b-4c40-a6fc-93899018d6c2', // Alice
    receiverName: 'Alice Designer',
    receiverAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    receiverHeadline: 'Senior UI/UX Designer & Design System Lead',
    offeredSkill: {
      name: 'SQL',
      level: 'Expert',
      category: 'Programming & Tech',
    },
    requestedSkill: {
      name: 'UI/UX',
      level: 'Expert',
      category: 'Design & Creative',
    },
    status: 'accepted',
    sessionFormat: 'Video Call',
    proposedSchedule: 'Weekdays & Weekends',
    initialMessage: 'Hi Alice, I need some quick design help for my dashboard. I can write your SQL queries in return!',
    createdAt: 'Recently',
    updatedAt: 'Recently',
    meetingLink: 'https://meet.skillswap.live/room-alice-charlie',
    objectives: [
      { id: 'obj-21', text: 'Charlie teaches SQL Indexing and joins', completed: true },
      { id: 'obj-22', text: 'Alice designs clean dashboard layout tokens', completed: true },
    ],
    messages: [
      {
        id: 'msg-seed-2',
        senderId: 'cf27f01d-10c3-4cdd-b3e4-0a9e61699c00',
        senderName: 'Charlie Data',
        senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
        text: 'Hi Alice, I need some quick design help for my dashboard. I can write your SQL queries in return!',
        timestamp: 'Recently',
      }
    ],
  },
];

export const INITIAL_REPORTS: AdminReport[] = [];

export const INITIAL_ANNOUNCEMENTS: PlatformAnnouncement[] = [
  {
    id: '76b0b5eb-06d9-45ef-b4cd-43d4efd1f986',
    title: 'Platform Announcement',
    content: 'Welcome to the Skill Swap Platform Hackathon Demo! Start exploring skills today.',
    type: 'info',
    isActive: true,
    date: 'Today',
    author: 'Platform Admin',
  },
];

export const INITIAL_NOTIFICATIONS: PlatformNotification[] = [
  {
    id: 'notif-1',
    userId: '47e26eab-001b-4c40-a6fc-93899018d6c2',
    title: 'New Swap Request Received',
    message: 'Bob The Dev sent you a proposal for Figma in exchange for Python.',
    type: 'swap_request',
    createdAt: 'Just now',
    read: false,
    swapId: 'swap-seed-1',
  },
];

export const INITIAL_SWAPS = INITIAL_SWAP_REQUESTS;
